mybatis:
  mapper-locations: classpath*:**/mappers/*Mapper.xml
  type-aliases-package: arki.springboot.sb06mybatis.pojo
server:
  port: 8000
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: 12345678
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/learning?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    useGlobalDataSourceStat: true
    username: root
    validationQuery: SELECT 1 FROM DUAL
